//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CM3036_CW_1504693
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int Id { get; set; }
        public string matricNum { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string gradeOne { get; set; }
        public string gradeTwo { get; set; }
        public string gradeThree { get; set; }
        public string gradeOverall { get; set; }
    }
}
